const arrWorldPart = [

	{ id: 'africa' 		, ua: 'Африка' 				, en: 'Africa' 			, }, 			
	{ id: 'amer_n' 		, ua: 'Північна Америка' 	, en: 'North America' 	, },
	{ id: 'amer_s' 		, ua: 'Південна Америка' 	, en: 'South America' 	, },
	{ id: 'antarctic' 	, ua: 'Антарктика' 			, en: 'Antarctic' 		, },
	{ id: 'arctic' 		, ua: 'Арктика' 			, en: 'Arctic' 			, },
	{ id: 'asia' 		, ua: 'Азія' 				, en: 'Asia' 			, },
	{ id: 'europe' 		, ua: 'Європа' 				, en: 'Europe' 			, },
	{ id: 'eurasia' 	, ua: 'Євразія' 			, en: 'Eurasia' 		, },
	{ id: 'oceania' 	, ua: 'Океанія' 			, en: 'Oceania' 		, },

];




let objWorldPart = {};
arrWorldPart.forEach( k => {
	objWorldPart[ k.id ] = k;
});












const arrCountry = [


/*

africa		
amer_n
amer_s
antarctic
arctic
asia
europe
eurasia
oceania

*/









/*

https://uk.wikipedia.org/wiki/ISO_3166-1

// неіснуючі країни
https://uk.wikipedia.org/wiki/ISO_3166-3









{
	id: '',
	title: { ua: '', en: '', },
	geo: { capital: '', part: '', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	internet: { wiki_ua: '', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 0, year: 2022, },
	area: 0,
},


decl - Декларация о нейтралитете
ind - день независимости
state - день государства
not_exist - не существует

День проголошення

*/






{
	id: 'aus', // symbol: { flag: 1, coa: 1, coa_big: 1, }, // coa - Coat of Arms
	title: { ua: 'Австралія', en: 'Australia', },
	geo: { capital: 'canberra', part: 'oceania', }, 
	code: { iso: '036', iso2: 'au', iso3: 'AUS', ean: '93', phone: '+61', },
	internet: { wiki_ua: '%D0%90%D0%B2%D1%81%D1%82%D1%80%D0%B0%D0%BB%D1%96%D1%8F', },
	independence_day: { dm: '2601', descr: 'state', wiki_ua: '', },
	population: { count: 25250000, year: 2019, },
	area: 7688287,
},
{
	id: 'aut', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Австрія', en: 'Austria', },
	geo: { capital: 'wien', part: 'europe', },
	code: { iso: '040', iso2: 'at', iso3: 'AUT', ean: '90-91', phone: '+43', },
	internet: { wiki_ua: '%D0%90%D0%B2%D1%81%D1%82%D1%80%D1%96%D1%8F', },
	independence_day: { dm: '2610', descr: 'decl', note: 'Декларация о нейтралитете', },
	population: { count: 8857960, year: 2018, },
	area: 83871,
},
{
	id: 'aze',
	title: { ua: 'Азербайджан', en: 'Azerbaijan', },
	geo: { capital: 'baku', part: 'eurasia', },
	code: { iso: '031', iso2: 'az', iso3: 'AZE', ean: '476', phone: '+994', },
	internet: { wiki_ua: '%D0%90%D0%B7%D0%B5%D1%80%D0%B1%D0%B0%D0%B9%D0%B4%D0%B6%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 9981457, year: 2019, },
	area: 86600,
},
{
	id: 'alb', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Албанія', en: 'Albania', },
	geo: { capital: 'tirana', part: 'europe', },
	code: { iso: '008', iso2: 'al', iso3: 'ALB', ean: '530', phone: '+355', },
	internet: { wiki_ua: '%D0%90%D0%BB%D0%B1%D0%B0%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'dza',
	title: { ua: 'Алжир', en: 'Algeria', },
	geo: { capital: 'algeria', part: 'africa', },
	code: { iso: '012', iso2: 'dz', iso3: 'DZA', ean: '613', phone: '+213', },
	internet: { wiki_ua: '%D0%90%D0%BB%D0%B6%D0%B8%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'ago',
	title: { ua: 'Ангола', en: 'Angola', },
	geo: { capital: 'luanda', part: 'africa', },
	code: { iso: '024', iso2: 'ao', iso3: 'AGO', ean: '', phone: '+244', },
	internet: { wiki_ua: '%D0%90%D0%BD%D0%B3%D0%BE%D0%BB%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'and', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Андорра', en: 'Andorra', },
	geo: { capital: 'andorra_la_vella', part: 'europe', },
	code: { iso: '020', iso2: 'ad', iso3: 'AND', ean: '', phone: '+376', },
	internet: { wiki_ua: '%D0%90%D0%BD%D0%B4%D0%BE%D1%80%D1%80%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'arg',
	title: { ua: 'Аргентина', en: 'Argentina', },
	geo: { capital: 'buenos_aires', part: 'amer_s', },
	code: { iso: '032', iso2: 'ar', iso3: 'ARG', ean: '779', phone: '+54', },
	internet: { wiki_ua: '%D0%90%D1%80%D0%B3%D0%B5%D0%BD%D1%82%D0%B8%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 45195774, year: 2020, },
	area: 2766890,
},
{
	id: 'afg',
	title: { ua: 'Афганістан', en: 'Afghanistan', },
	geo: { capital: 'kabul', part: 'asia', },
	code: { iso: '004', iso2: 'af', iso3: 'AFG', ean: '', phone: '+93', },
	internet: { wiki_ua: '%D0%90%D1%84%D0%B3%D0%B0%D0%BD%D1%96%D1%81%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 33928493, year: 2020, },
	area: 652230,
},
{
	id: 'brb',
	title: { ua: 'Барбадос', en: 'Barbados', },
	geo: { capital: 'bridgetown', part: 'amer_n', },
	code: { iso: '', iso2: 'bb', iso3: 'BRB', ean: '', phone: '+1-246', },
	internet: { wiki_ua: '%D0%91%D0%B0%D1%80%D0%B1%D0%B0%D0%B4%D0%BE%D1%81', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bgd',
	title: { ua: 'Бангладеш', en: 'Bangladesh', },
	geo: { capital: 'dhaka', part: 'asia', },
	code: { iso: '050', iso2: 'bd', iso3: 'BGD', ean: '', phone: '+880', },
	internet: { wiki_ua: '%D0%91%D0%B0%D0%BD%D0%B3%D0%BB%D0%B0%D0%B4%D0%B5%D1%88', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bhr',
	title: { ua: 'Бахрейн', en: 'Bahrain', },
	geo: { capital: 'manama', part: 'asia', },
	code: { iso: '048', iso2: 'bh', iso3: 'BHR', ean: '', phone: '+973', },
	internet: { wiki_ua: '%D0%91%D0%B0%D1%85%D1%80%D0%B5%D0%B9%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'blz',
	title: { ua: 'Беліз', en: 'Belize', },
	geo: { capital: 'belmopan', part: 'amer_n', },
	code: { iso: '084', iso2: 'bz', iso3: 'BLZ', ean: '', phone: '+501', },
	internet: { wiki_ua: '%D0%91%D0%B5%D0%BB%D1%96%D0%B7', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bel', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Бельгія', en: 'Belgium', },
	geo: { capital: 'brussels', part: 'europe', },
	code: { iso: '056', iso2: 'be', iso3: 'BEL', ean: '54', phone: '+32', },
	internet: { wiki_ua: '%D0%91%D0%B5%D0%BB%D1%8C%D0%B3%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 11481000, year: 2019, },
	area: 32547,
},
{
	id: 'ben',
	title: { ua: 'Бенін', en: 'Benin', },
	geo: { capital: 'porto_novo', part: 'africa', },
	code: { iso: '204', iso2: 'bj', iso3: 'BEN', ean: '', phone: '+229', },
	internet: { wiki_ua: '%D0%91%D0%B5%D0%BD%D1%96%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'blr', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Білорусь', en: 'Belarus', },
	geo: { capital: 'minsk', part: 'europe', },
	code: { iso: '112', iso2: 'by', iso3: 'BLR', ean: '481', phone: '+375', },
	internet: { wiki_ua: '%D0%91%D1%96%D0%BB%D0%BE%D1%80%D1%83%D1%81%D1%8C', },
	independence_day: { dm: '0307', descr: '', note: '', wiki_ua: '', },
	population: { count: 9475600, year: 2019, },
	area: 207600,
},
{
	id: 'bgr', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Болгарія', en: 'Bulgaria', },
	geo: { capital: 'sofia', part: 'europe', },
	code: { iso: '100', iso2: 'bg', iso3: 'BGR', ean: '380', phone: '+359', },
	internet: { wiki_ua: '%D0%91%D0%BE%D0%BB%D0%B3%D0%B0%D1%80%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bol',
	title: { ua: 'Болівія', en: 'Bolivia', },
	geo: { capital: 'sucre', part: 'amer_s', },
	code: { iso: '068', iso2: 'bo', iso3: 'BOL', ean: '', phone: '+591', },
	internet: { wiki_ua: '%D0%91%D0%BE%D0%BB%D1%96%D0%B2%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bih', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Боснія і Герцеговина', en: 'Bosnia and Herzegovina', },
	geo: { capital: 'sarajevo', part: 'europe', },
	code: { iso: '070', iso2: 'ba', iso3: 'BIH', ean: '387', phone: '+387', },
	internet: { wiki_ua: '%D0%91%D0%BE%D1%81%D0%BD%D1%96%D1%8F_%D1%96_%D0%93%D0%B5%D1%80%D1%86%D0%B5%D0%B3%D0%BE%D0%B2%D0%B8%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bwa',
	title: { ua: 'Ботсвана', en: 'Botswana', },
	geo: { capital: 'gaborone', part: 'africa', },
	code: { iso: '072', iso2: 'bw', iso3: 'BWA', ean: '', phone: '+267', },
	internet: { wiki_ua: '%D0%91%D0%BE%D1%82%D1%81%D0%B2%D0%B0%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'bra',
	title: { ua: 'Бразилія', en: 'Brazil', },
	geo: { capital: 'brasilia', part: 'amer_s', },
	code: { iso: '076', iso2: 'br', iso3: 'BRA', ean: '789', phone: '+55', },
	internet: { wiki_ua: '%D0%91%D1%80%D0%B0%D0%B7%D0%B8%D0%BB%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 214047375, year: 2022, },
	area: 8515767,
},
{
	id: 'brn',
	title: { ua: 'Бруней', en: 'Brunei', },
	geo: { capital: 'bandar_seri_begawan', part: 'asia', },
	code: { iso: '096', iso2: 'bn', iso3: 'BRN', ean: '', phone: '+673', },
	internet: { wiki_ua: '%D0%91%D1%80%D1%83%D0%BD%D0%B5%D0%B9', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'btn',
	title: { ua: 'Бутан', en: 'Butane', },
	geo: { capital: 'thimphu', part: 'asia', },
	code: { iso: '064', iso2: 'bt', iso3: 'BTN', ean: '', phone: '+975', },
	internet: { wiki_ua: '%D0%91%D1%83%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'vat', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Ватикан', en: 'Vatican', },
	geo: { part: 'europe', },
	code: { iso: '336', iso2: 'va', iso3: 'VAT', ean: '', phone: '+39,+379', },
	internet: { wiki_ua: '%D0%92%D0%B0%D1%82%D0%B8%D0%BA%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 800, year: 2007, },
	area: 0.521,
},
{
	id: 'gbr', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Велика Британія', en: 'United Kingdom', },
	geo: { capital: 'london', part: 'europe', },
	code: { iso: '826', iso2: 'gb', iso3: 'GBR', ean: '50', phone: '+44', },
	internet: { wiki_ua: '%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%B0_%D0%91%D1%80%D0%B8%D1%82%D0%B0%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 67791400, year: 2022, },
	area: 242495,
},
{
	id: 'ven',
	title: { ua: 'Венесуела', en: 'Venezuela', },
	geo: { capital: 'caracas', part: 'amer_s', },
	code: { iso: '862', iso2: 've', iso3: 'VEN', ean: '759', phone: '+58', },
	internet: { wiki_ua: '%D0%92%D0%B5%D0%BD%D0%B5%D1%81%D1%83%D0%B5%D0%BB%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'vnm',
	title: { ua: 'В\'єтнам', en: 'Vietnam', },
	geo: { capital: 'hanoi', part: 'asia', },
	code: { iso: '704', iso2: 'vn', iso3: 'VNM', ean: '893', phone: '+84', },
	internet: { wiki_ua: '%D0%92%27%D1%94%D1%82%D0%BD%D0%B0%D0%BC', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 103808319, year: 2022, },
	area: 331689,
},
{
	id: 'arm',
	title: { ua: 'Вірменія', en: 'Armenia', },
	geo: { capital: 'yerevan', part: 'asia', },
	code: { iso: '051', iso2: 'am', iso3: 'ARM', ean: '485', phone: '+374', },
	internet: { wiki_ua: '%D0%92%D1%96%D1%80%D0%BC%D0%B5%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 3009800, year: 2022, },
	area: 29800,
},
{
	id: 'gab',
	title: { ua: 'Габон', en: 'Gabon', },
	geo: { capital: 'libreville', part: 'africa', },
	code: { iso: '266', iso2: 'ga', iso3: 'GAB', ean: '', phone: '+241', },
	internet: { wiki_ua: '%D0%93%D0%B0%D0%B1%D0%BE%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'hti',
	title: { ua: 'Гаїті', en: 'Haiti', },
	geo: { capital: 'port_au_prince', part: 'amer_n', },
	code: { iso: '', iso2: 'ht', iso3: 'HTI', ean: '', phone: '+509', },
	internet: { wiki_ua: '%D0%93%D0%B0%D1%97%D1%82%D1%96', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'gmb',
	title: { ua: 'Гамбія', en: 'Gambia', },
	geo: { capital: 'banjul', part: 'africa', },
	code: { iso: '270', iso2: 'gm', iso3: 'GMB', ean: '', phone: '+220', },
	internet: { wiki_ua: '%D0%93%D0%B0%D0%BC%D0%B1%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'gha',
	title: { ua: 'Гана', en: 'Ghana', },
	geo: { capital: 'accra', part: 'africa', },
	code: { iso: '288', iso2: 'gh', iso3: 'GHA', ean: '', phone: '+233', },
	internet: { wiki_ua: '%D0%93%D0%B0%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'guy',
	title: { ua: 'Гаяна', en: 'Guyana', },
	geo: { capital: 'georgetown', part: 'amer_s', },
	code: { iso: '328', iso2: 'gy', iso3: 'GUY', ean: '', phone: '+592', },
	internet: { wiki_ua: '%D0%93%D0%B0%D1%8F%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'gtm',
	title: { ua: 'Гватемала', en: 'Guatemala', },
	geo: { capital: 'guatemala', part: 'amer_n', },
	code: { iso: '320', iso2: 'gt', iso3: 'GTM', ean: '740', phone: '+502', },
	internet: { wiki_ua: '%D0%93%D0%B2%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D0%BB%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'gin',
	title: { ua: 'Гвінея', en: 'Guinea', },
	geo: { capital: 'conakry', part: 'africa', },
	code: { iso: '324', iso2: 'gn', iso3: 'GIN', ean: '', phone: '+224', },
	internet: { wiki_ua: '%D0%93%D0%B2%D1%96%D0%BD%D0%B5%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'gnb',
	title: { ua: 'Гвінея-Бісау', en: 'Guinea-Bissau', },
	geo: { capital: 'bissau', part: 'africa', },
	code: { iso: '624', iso2: 'gw', iso3: 'GNB', ean: '', phone: '+245', },
	internet: { wiki_ua: '%D0%93%D0%B2%D1%96%D0%BD%D0%B5%D1%8F-%D0%91%D1%96%D1%81%D0%B0%D1%83', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'gib', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Гібралтар', en: 'Gibraltar', },
	geo: { capital: '', part: 'europe', },
	code: { iso: '', iso2: 'gi', iso3: 'GIB', ean: '', phone: '+350', },
	internet: { wiki_ua: '%D0%93%D1%96%D0%B1%D1%80%D0%B0%D0%BB%D1%82%D0%B0%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'hnd',
	title: { ua: 'Гондурас', en: 'Honduras', },
	geo: { capital: 'tegucigalpa', part: 'amer_n', },
	code: { iso: '', iso2: 'hn', iso3: 'HND', ean: '742', phone: '+504', },
	internet: { wiki_ua: '%D0%93%D0%BE%D0%BD%D0%B4%D1%83%D1%80%D0%B0%D1%81', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'hkg',
	title: { ua: 'Гонконг', en: 'Hong Kong', },
	geo: { part: 'asia', },
	code: { iso: '344', iso2: 'hk', iso3: 'HKG', ean: '489', phone: '+852', },
	internet: { wiki_ua: '%D0%93%D0%BE%D0%BD%D0%BA%D0%BE%D0%BD%D0%B3', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 7055071, year: 2010, },
	area: 1104,
},
{
	id: 'grl',
	title: { ua: 'Гренландія', en: 'Greenland', },
	geo: { capital: 'nuuk', part: '', },
	code: { iso: '304', iso2: 'gl', iso3: 'GRL', ean: '', phone: '+299', },
	internet: { wiki_ua: '%D0%93%D1%80%D0%B5%D0%BD%D0%BB%D0%B0%D0%BD%D0%B4%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'grc', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Греція', en: 'Greece', },
	geo: { capital: 'athens', part: 'europe', },
	code: { iso: '300', iso2: 'gr', iso3: 'GRC', ean: '520', phone: '+30', },
	internet: { wiki_ua: '%D0%93%D1%80%D0%B5%D1%86%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 10768477, year: 2017, },
	area: 131957,
},
{
	id: 'geo', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Грузія', en: 'Georgia', },
	geo: { capital: 'tbilisi', part: 'europe', },
	code: { iso: '268', iso2: 'ge', iso3: 'GEO', ean: '486', phone: '+995', },
	internet: { wiki_ua: '%D0%93%D1%80%D1%83%D0%B7%D1%96%D1%8F', },	
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 3729500, year: 2015, },
	area: 69700,
},
{
	id: 'dnk', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Данія', en: 'Denmark', },
	geo: { capital: 'copenhagen', part: 'europe', },
	code: { iso: '208', iso2: 'dk', iso3: 'DNK', ean: '57', phone: '+45', },
	internet: { wiki_ua: '%D0%94%D0%B0%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 5792202, year: 2020, },
	area: 43094,
},
{
	id: 'dji',
	title: { ua: 'Джибуті', en: 'Djibouti', },
	geo: { capital: 'djibouti', part: 'africa', },
	code: { iso: '262', iso2: 'dj', iso3: 'DJI', ean: '', phone: '+253', },
	internet: { wiki_ua: '%D0%94%D0%B6%D0%B8%D0%B1%D1%83%D1%82%D1%96', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'dma',
	title: { ua: 'Домініка', en: 'Dominica', },
	geo: { capital: 'rose', part: 'amer_n', },
	code: { iso: '212', iso2: 'dm', iso3: 'DMA', ean: '', phone: '+1767', },
	internet: { wiki_ua: '%D0%94%D0%BE%D0%BC%D1%96%D0%BD%D1%96%D0%BA%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'ecu',
	title: { ua: 'Еквадор', en: 'Ecuador', },
	geo: { capital: 'quito', part: 'amer_s', },
	code: { iso: '218', iso2: 'ec', iso3: 'ECU', ean: '786', phone: '+593', },
	internet: { wiki_ua: '%D0%95%D0%BA%D0%B2%D0%B0%D0%B4%D0%BE%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 16385068, year: 2016, },
	area: 256370,
},
{
	id: 'gnq',
	title: { ua: 'Екваторіальна Гвінея', en: 'Equatorial Guinea', },
	geo: { capital: 'malabo', part: 'africa', },
	code: { iso: '226', iso2: 'gq', iso3: 'GNQ', ean: '', phone: '+240', },
	internet: { wiki_ua: '%D0%95%D0%BA%D0%B2%D0%B0%D1%82%D0%BE%D1%80%D1%96%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0_%D0%93%D0%B2%D1%96%D0%BD%D0%B5%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 1454789, year: 2020, },
	area: 28051,
},
{
	id: 'eri',
	title: { ua: 'Еритрея', en: 'Eritrea', },
	geo: { capital: 'asmer', part: 'africa', },
	code: { iso: '232', iso2: 'er', iso3: 'ERI', ean: '', phone: '+291', },
	internet: { wiki_ua: '%D0%95%D1%80%D0%B8%D1%82%D1%80%D0%B5%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 6086495, year: 2012, },
	area: 117600,
},
{
	id: 'est', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Естонія', en: 'Estonia', },
	geo: { capital: 'tallinn', part: 'europe', },
	code: { iso: '233', iso2: 'ee', iso3: 'EST', ean: '474', phone: '+372', },
	internet: { wiki_ua: '%D0%95%D1%81%D1%82%D0%BE%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 1340194, year: 2010, },
	area: 45226,
},
{
	id: 'eth',
	title: { ua: 'Ефіопія', en: 'Ethiopia', },
	geo: { capital: 'addis_ababa', part: 'africa', },
	code: { iso: '231', iso2: 'et', iso3: 'ETH', ean: '', phone: '+251', },
	internet: { wiki_ua: '%D0%95%D1%84%D1%96%D0%BE%D0%BF%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 112269301, year: 2009, },
	area: 1104300,
},
{
	id: 'egy',
	title: { ua: 'Єгипет', en: 'Egypt', },
	geo: { capital: 'cairo', part: 'africa', },
	code: { iso: '', iso2: 'eg', iso3: 'EGY', ean: '622', phone: '+20', },
	internet: { wiki_ua: '%D0%84%D0%B3%D0%B8%D0%BF%D0%B5%D1%82', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'yem',
	title: { ua: 'Ємен', en: 'Yemen', },
	geo: { capital: 'sana', part: 'asia', },
	code: { iso: '', iso2: 'ye', iso3: 'YEM', ean: '', phone: '+967', },
	internet: { wiki_ua: '%D0%84%D0%BC%D0%B5%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'zmb',
	title: { ua: 'Замбія', en: 'Zambia', },
	geo: { capital: 'lusaka', part: 'africa', },
	code: { iso: '894', iso2: 'zm', iso3: 'ZMB', ean: '', phone: '+260', },
	internet: { wiki_ua: '%D0%97%D0%B0%D0%BC%D0%B1%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'zwe',
	title: { ua: 'Зімбабве', en: 'Zimbabwe', },
	geo: { capital: 'harare', part: 'africa', },
	code: { iso: '716', iso2: 'zw', iso3: 'ZWE', ean: '', phone: '+263', },
	internet: { wiki_ua: '%D0%97%D1%96%D0%BC%D0%B1%D0%B0%D0%B1%D0%B2%D0%B5', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'isr',
	title: { ua: 'Ізраїль', en: 'Israel', },
	geo: { capital: 'jerusalem', part: 'asia', },
	code: { iso: '376', iso2: 'il', iso3: 'ISR', ean: '729', phone: '+972', },
	internet: { wiki_ua: '%D0%86%D0%B7%D1%80%D0%B0%D1%97%D0%BB%D1%8C', },
	independence_day: { dm: '1405', descr: '', note: '', wiki_ua: '', },
	population: { count: 9291000, year: 2021, },
	area: 20770,
},
{
	id: 'ind',
	title: { ua: 'Індія', en: 'India', },
	geo: { capital: 'new_delhi', part: 'asia', },
	code: { iso: '356', iso2: 'in', iso3: 'IND', ean: '890', phone: '+91', },
	internet: { wiki_ua: '%D0%86%D0%BD%D0%B4%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 1414843757, year: 2022, },
	area: 3287590,
},
{
	id: 'idn',
	title: { ua: 'Індонезія', en: 'Indonesia', },
	geo: { capital: 'jakarta', part: 'asia', },
	code: { iso: '', iso2: 'id', iso3: 'IDN', ean: '899', phone: '+62', },
	internet: { wiki_ua: '%D0%86%D0%BD%D0%B4%D0%BE%D0%BD%D0%B5%D0%B7%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'irq',
	title: { ua: 'Ірак', en: 'Iraq', },
	geo: { capital: 'baghdad', part: 'asia', },
	code: { iso: '368', iso2: 'iq', iso3: 'IRQ', ean: '', phone: '+964', },
	internet: { wiki_ua: '%D0%86%D1%80%D0%B0%D0%BA', },
	independence_day: { dm: '0310', descr: '', note: '', wiki_ua: '', },
	population: { count: 39127900, year: 2019, },
	area: 437072,
},
{
	id: 'irn',
	title: { ua: 'Іран', en: 'Iran', },
	geo: { capital: 'tehran', part: 'asia', },
	code: { iso: '364', iso2: 'ir', iso3: 'IRN', ean: '626', phone: '+98', },
	internet: { wiki_ua: '%D0%86%D1%80%D0%B0%D0%BD', },
	independence_day: { dm: '0104', descr: '', note: '', wiki_ua: '', },
	population: { count: 79966230, year: 2017, },
	area: 1648195,
},
{
	id: 'irl', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Ірландія', en: 'Ireland', },
	geo: { capital: 'dublin', part: 'europe', },
	code: { iso: '372', iso2: 'ie', iso3: 'IRL', ean: '539', phone: '+353', },
	internet: { wiki_ua: '%D0%86%D1%80%D0%BB%D0%B0%D0%BD%D0%B4%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'isl', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Ісландія', en: 'Iceland', },
	geo: { capital: 'reykjavik', part: 'europe', },
	code: { iso: '', iso2: 'is', iso3: 'ISL', ean: '569', phone: '+354', },
	internet: { wiki_ua: '%D0%86%D1%81%D0%BB%D0%B0%D0%BD%D0%B4%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'esp', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Іспанія', en: 'Spain', },
	geo: { capital: 'madrid', part: 'europe', },
	code: { iso: '724', iso2: 'es', iso3: 'ESP', ean: '84', phone: '+34', },
	internet: { wiki_ua: '%D0%86%D1%81%D0%BF%D0%B0%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 47500000, year: 2021, },
	area: 504645,
},
{
	id: 'ita', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Італія', en: 'Italy', },
	geo: { capital: 'rome', part: 'europe', },
	code: { iso: '380', iso2: 'it', iso3: 'ITA', ean: '80-83', phone: '+39', },
	internet: { wiki_ua: '%D0%86%D1%82%D0%B0%D0%BB%D1%96%D1%8F', },
	independence_day: { dm: '0206', descr: '', note: 'День проголошення', wiki_ua: '%D0%94%D0%B5%D0%BD%D1%8C_%D0%BF%D1%80%D0%BE%D0%B3%D0%BE%D0%BB%D0%BE%D1%88%D0%B5%D0%BD%D0%BD%D1%8F_%D0%86%D1%82%D0%B0%D0%BB%D1%96%D0%B9%D1%81%D1%8C%D0%BA%D0%BE%D1%97_%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B8', },
	population: { count: 60588306, year: 2019, },
	area: 301338,
},
{
	id: 'jor',
	title: { ua: 'Йорданія', en: 'Jordan', },
	geo: { capital: 'amman', part: 'asia', },
	code: { iso: '', iso2: 'jo', iso3: 'JOR', ean: '625', phone: '+962', },
	internet: { wiki_ua: '%D0%99%D0%BE%D1%80%D0%B4%D0%B0%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'kaz',
	title: { ua: 'Казахстан', en: 'Kazakhstan', },
	geo: { capital: 'nur_sultan', part: 'asia', },
	code: { iso: '398', iso2: 'kz', iso3: 'KAZ', ean: '487', phone: '+7', },
	internet: { wiki_ua: '%D0%9A%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 18690115, year: 2020, },
	area: 2724900,
	note: 'Телефонный код как в России',
},
{
	id: 'khm',
	title: { ua: 'Камбоджа', en: 'Cambodia', },
	geo: { capital: 'phnom_penh', part: 'asia', },
	code: { iso: '116', iso2: 'kh', iso3: 'KHM', ean: '', phone: '+855', },
	internet: { wiki_ua: '%D0%9A%D0%B0%D0%BC%D0%B1%D0%BE%D0%B4%D0%B6%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'cmr',
	title: { ua: 'Камерун', en: 'Cameroon', },
	geo: { capital: 'yaounde', part: 'africa', },
	code: { iso: '120', iso2: 'cm', iso3: 'CMR', ean: '', phone: '+237', },
	internet: { wiki_ua: '%D0%9A%D0%B0%D0%BC%D0%B5%D1%80%D1%83%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'can',
	title: { ua: 'Канада', en: 'Canada', },
	geo: { capital: 'ottawa', part: 'amer_n', },
	code: { iso: '124', iso2: 'ca', iso3: 'CAN', ean: '', phone: '+1', },
	internet: { wiki_ua: '%D0%9A%D0%B0%D0%BD%D0%B0%D0%B4%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 37067011, year: 2018, },
	area: 9984670,	
},
{
	id: 'qat',
	title: { ua: 'Катар', en: 'Qatar', },
	geo: { capital: 'doha', part: 'asia', },
	code: { iso: '634', iso2: 'qa', iso3: 'QAT', ean: '', phone: '+974', },
	internet: { wiki_ua: '%D0%9A%D0%B0%D1%82%D0%B0%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'ken',
	title: { ua: 'Кенія', en: 'Kenya', },
	geo: { capital: 'nairobi', part: 'africa', },
	code: { iso: '404', iso2: 'ke', iso3: 'KEN', ean: '616', phone: '+254', },
	internet: { wiki_ua: '%D0%9A%D0%B5%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'kgz',
	title: { ua: 'Киргизстан', en: 'Kyrgyzstan', },
	geo: { capital: 'bishkek', part: 'asia', },
	code: { iso: '417', iso2: 'kg', iso3: 'KGZ', ean: '470', phone: '+996', },
	internet: { wiki_ua: '%D0%9A%D0%B8%D1%80%D0%B3%D0%B8%D0%B7%D1%81%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 4753003, year: 2000, },
	area: 198500,
},
{
	id: 'chn',
	title: { ua: 'Китай', en: 'China', },
	geo: { capital: 'beijing', part: 'asia', },
	code: { iso: '156', iso2: 'cn', iso3: 'CHN', ean: '690-693', phone: '+86', },
	internet: { wiki_ua: '%D0%9A%D0%B8%D1%82%D0%B0%D0%B9%D1%81%D1%8C%D0%BA%D0%B0_%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%B0_%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 1411780000, year: 2021, },
	area: 9596960,
},
{
	id: 'cyp',
	title: { ua: 'Кіпр', en: 'Cyprus', },
	geo: { capital: 'nicosia', part: 'asia', },
	code: { iso: '196', iso2: 'cy', iso3: 'CYP', ean: '529', phone: '+357', },
	internet: { wiki_ua: '%D0%9A%D1%96%D0%BF%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 798045, year: 2010, },
	area: 9248,
},
{
	id: 'kir',
	title: { ua: 'Кірибаті', en: 'Kiribati', },
	geo: { capital: 'south_tarawa', part: 'oceania', },
	code: { iso: '296', iso2: 'ki', iso3: 'KIR', ean: '', phone: '+686', },
	internet: { wiki_ua: '%D0%9A%D1%96%D1%80%D0%B8%D0%B1%D0%B0%D1%82%D1%96', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'col',
	title: { ua: 'Колумбія', en: 'Colombia', },
	geo: { capital: 'bogota', part: 'amer_s', },
	code: { iso: '170', iso2: 'co', iso3: 'COL', ean: '770', phone: '+57', },
	internet: { wiki_ua: '%D0%9A%D0%BE%D0%BB%D1%83%D0%BC%D0%B1%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'cod',
	title: { ua: 'ДР Конго', en: 'Democratic Republic of the Congo', },
	geo: { capital: 'kinshasa', part: 'africa', },
	code: { iso: '180', iso2: 'cd', iso3: 'COD', ean: '', phone: '+243', },
	internet: { wiki_ua: '%D0%94%D0%B5%D0%BC%D0%BE%D0%BA%D1%80%D0%B0%D1%82%D0%B8%D1%87%D0%BD%D0%B0_%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B0_%D0%9A%D0%BE%D0%BD%D0%B3%D0%BE', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'cog',
	title: { ua: 'Конго', en: 'Republic of the Congo', },
	geo: { capital: 'brazzaville', part: 'africa', },
	code: { iso: '178', iso2: 'cg', iso3: 'COG', ean: '', phone: '+242', },
	internet: { wiki_ua: '%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B0_%D0%9A%D0%BE%D0%BD%D0%B3%D0%BE', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'cri',
	title: { ua: 'Коста-Рика', en: 'Costa Rica', },
	geo: { capital: 'san_jose', part: 'amer_n', },
	code: { iso: '188', iso2: 'cr', iso3: 'CRI', ean: '744', phone: '+506', },
	internet: { wiki_ua: '%D0%9A%D0%BE%D1%81%D1%82%D0%B0-%D0%A0%D0%B8%D0%BA%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'civ',
	title: { ua: 'Кот-д\'Ивуар', en: 'Ivory Coast', },
	geo: { capital: 'yamoussoukro', part: 'africa', },
	code: { iso: '384', iso2: 'ci', iso3: 'CIV', ean: '', phone: '+225', },
	internet: { wiki_ua: '%D0%9A%D0%BE%D1%82-%D0%B4%27%D0%86%D0%B2%D1%83%D0%B0%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'cub',
	title: { ua: 'Куба', en: 'Cuba', },
	geo: { capital: 'havana', part: 'amer_n', },
	code: { iso: '192', iso2: 'cu', iso3: 'CUB', ean: '850', phone: '+53', },
	internet: { wiki_ua: '%D0%9A%D1%83%D0%B1%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 11239004, year: 2015, },
	area: 110861,
},
{
	id: 'kwt',
	title: { ua: 'Кувейт', en: 'Kuwait', },
	geo: { capital: 'el_kuwait', part: 'asia', },
	code: { iso: '414', iso2: 'kw', iso3: 'KWT', ean: '', phone: '+965', },
	internet: { wiki_ua: '%D0%9A%D1%83%D0%B2%D0%B5%D0%B9%D1%82', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'lao',
	title: { ua: 'Лаос', en: 'Laos', },
	geo: { capital: 'vientiane', part: 'asia', },
	code: { iso: '418', iso2: 'la', iso3: 'LAO', ean: '', phone: '+856', },
	internet: { wiki_ua: '%D0%9B%D0%B0%D0%BE%D1%81', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'lva', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Латвія', en: 'Latvia', },
	geo: { capital: 'riga', part: 'europe', },
	code: { iso: '428', iso2: 'lv', iso3: 'LVA', ean: '475', phone: '+371', },
	internet: { wiki_ua: '%D0%9B%D0%B0%D1%82%D0%B2%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 1907675, year: 2020, },
	area: 64589,
},
{
	id: 'lso',
	title: { ua: 'Лесото', en: 'Lesotho', },
	geo: { capital: 'maseru', part: 'africa', },
	code: { iso: '426', iso2: 'ls', iso3: 'LSO', ean: '', phone: '+266', },
	internet: { wiki_ua: '%D0%9B%D0%B5%D1%81%D0%BE%D1%82%D0%BE', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'ltu', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Литва', en: 'Lithuania', },
	geo: { capital: 'vilnius', part: 'europe', },
	code: { iso: '440', iso2: 'lt', iso3: 'LTU', ean: '477', phone: '+370', },
	internet: { wiki_ua: '%D0%9B%D0%B8%D1%82%D0%B2%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 2784279, year: 2021, },
	area: 65300,
},
{
	id: 'lbr',
	title: { ua: 'Ліберія', en: 'Liberia', },
	geo: { capital: 'monrovia', part: 'africa', },
	code: { iso: '430', iso2: 'lr', iso3: 'LBR', ean: '', phone: '+231', },
	internet: { wiki_ua: '%D0%9B%D1%96%D0%B1%D0%B5%D1%80%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'lbn',
	title: { ua: 'Ліван', en: 'Lebanon', },
	geo: { capital: 'beirut', part: 'asia', },
	code: { iso: '422', iso2: 'lb', iso3: 'LBN', ean: '528', phone: '+961', },
	internet: { wiki_ua: '%D0%9B%D1%96%D0%B2%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'lby',
	title: { ua: 'Лівія', en: 'Libya', },
	geo: { capital: 'tripoli', part: 'africa', },
	code: { iso: '434', iso2: 'ly', iso3: 'LBY', ean: '', phone: '+218', },
	internet: { wiki_ua: '%D0%9B%D1%96%D0%B2%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 5670688, year: 2006, },
	area: 1759540,
},
{
	id: 'lie', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Ліхтенштейн', en: 'Liechtenstein', },
	geo: { capital: 'vaduz', part: 'europe', },
	code: { iso: '438', iso2: 'li', iso3: 'LIE', ean: '', phone: '+423', },
	internet: { wiki_ua: '%D0%9B%D1%96%D1%85%D1%82%D0%B5%D0%BD%D1%88%D1%82%D0%B5%D0%B9%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 38896, year: 2020, },
	area: 160,
},
{
	id: 'lux', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Люксембург', en: 'Luxembourg', },
	geo: { capital: 'luxembourg', part: 'europe', },
	code: { iso: '442', iso2: 'lu', iso3: 'LUX', ean: '54', phone: '+352', },
	internet: { wiki_ua: '%D0%9B%D1%8E%D0%BA%D1%81%D0%B5%D0%BC%D0%B1%D1%83%D1%80%D0%B3', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 613900, year: 2019, },
	area: 2586,
},
{
	id: 'mrt',
	title: { ua: 'Мавританія', en: 'Mauritania', },
	geo: { capital: 'nouakchott', part: 'africa', },
	code: { iso: '478', iso2: 'mr', iso3: 'MRT', ean: '', phone: '+222', },
	internet: { wiki_ua: '%D0%9C%D0%B0%D0%B2%D1%80%D0%B8%D1%82%D0%B0%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 3359185, year: 2012, },
	area: 1030700,
},
{
	id: 'mdg',
	title: { ua: 'Мадагаскар', en: 'Madagascar', },
	geo: { capital: 'antananarivo', part: 'africa', },
	code: { iso: '450', iso2: 'mg', iso3: 'MDG', ean: '', phone: '+261', },
	internet: { wiki_ua: '%D0%9C%D0%B0%D0%B4%D0%B0%D0%B3%D0%B0%D1%81%D0%BA%D0%B0%D1%80', },
	independence_day: { dm: '2606', descr: '', note: '', wiki_ua: '', },
	population: { count: 26262313, year: 2019, },
	area: 587041,
},
{
	id: 'mkd', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Македонія', en: 'Macedonia', },
	geo: { capital: 'skopje', part: 'europe', },
	code: { iso: '807', iso2: 'mk', iso3: 'MKD', ean: '531', phone: '+389', },
	internet: { wiki_ua: '%D0%9F%D1%96%D0%B2%D0%BD%D1%96%D1%87%D0%BD%D0%B0_%D0%9C%D0%B0%D0%BA%D0%B5%D0%B4%D0%BE%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 2103721, year: 2017, },
	area: 25713,
},
{
	id: 'mys',
	title: { ua: 'Малайзія', en: 'Malaysia', },
	geo: { capital: 'kuala_lumpur', part: 'asia', },
	code: { iso: '', iso2: 'my', iso3: 'MYS', ean: '955', phone: '+60', },
	internet: { wiki_ua: '%D0%9C%D0%B0%D0%BB%D0%B0%D0%B9%D0%B7%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 27140000, year: 2007, },
	area: 329847,
},
{
	id: 'mli',
	title: { ua: 'Малі', en: 'Mali', },
	geo: { capital: 'bamako', part: 'africa', },
	code: { iso: '466', iso2: 'ml', iso3: 'MLI', ean: '', phone: '+223', },
	internet: { wiki_ua: '%D0%9C%D0%B0%D0%BB%D1%96', },
	independence_day: { dm: '2209', descr: '', note: '', wiki_ua: '', },
	population: { count: 20250833, year: 2020, },
	area: 1240192,
},
{
	id: 'mlt', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Мальта', en: 'Malta', },
	geo: { capital: 'valletta', part: 'europe', },
	code: { iso: '470', iso2: 'mt', iso3: 'MLT', ean: '535', phone: '+356', },
	internet: { wiki_ua: '%D0%9C%D0%B0%D0%BB%D1%8C%D1%82%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'mar',
	title: { ua: 'Марокко', en: 'Morocco', },
	geo: { capital: 'rabat', part: 'africa', },
	code: { iso: '504', iso2: 'ma', iso3: 'MAR', ean: '611', phone: '+212', },
	internet: { wiki_ua: '%D0%9C%D0%B0%D1%80%D0%BE%D0%BA%D0%BA%D0%BE', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'mex',
	title: { ua: 'Мексика', en: 'Mexico', },
	geo: { capital: 'mexico', part: 'amer_n', },
	code: { iso: '484', iso2: 'mx', iso3: 'MEX', ean: '750', phone: '+52', },
	internet: { wiki_ua: '%D0%9C%D0%B5%D0%BA%D1%81%D0%B8%D0%BA%D0%B0', },
	independence_day: { dm: '1609', descr: 'ind', note: '', wiki_ua: '', },
	population: { count: 126577691, year: 2019, },
	area: 1972550,
},
{
	id: 'moz',
	title: { ua: 'Мозамбик', en: 'Mozambique', },
	geo: { capital: 'maputo', part: 'africa', },
	code: { iso: '508', iso2: 'mz', iso3: 'MOZ', ean: '', phone: '+258', },
	internet: { wiki_ua: '%D0%9C%D0%BE%D0%B7%D0%B0%D0%BC%D0%B1%D1%96%D0%BA', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'mda', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Молдова', en: 'Moldova', },
	geo: { capital: 'сhisinau', part: 'europe', },
	code: { iso: '498', iso2: 'md', iso3: 'MDA', ean: '484', phone: '+373', },
	internet: { wiki_ua: '%D0%9C%D0%BE%D0%BB%D0%B4%D0%BE%D0%B2%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 4035000, year: 2020, },
	area: 33843,
},
{
	id: 'mco', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Монако', en: 'Monaco', },
	geo: { capital: '', part: 'europe', },
	code: { iso: '492', iso2: 'mc', iso3: 'MCO', ean: '', phone: '+377', },
	internet: { wiki_ua: '%D0%9C%D0%BE%D0%BD%D0%B0%D0%BA%D0%BE', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 38400, year: 2014, },
	area: 2,
},
{
	id: 'mng',
	title: { ua: 'Монголія', en: 'Mongolia', },
	geo: { capital: 'ulaanbaatar', part: 'asia', },
	code: { iso: '496', iso2: 'mn', iso3: 'MNG', ean: '', phone: '+976', },
	internet: { wiki_ua: '%D0%9C%D0%BE%D0%BD%D0%B3%D0%BE%D0%BB%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 3353470, year: 2020, },
	area: 1564116,
},
{
	id: 'mmr',
	title: { ua: 'М\'янма', en: 'Myanmar', },
	geo: { capital: 'naypedo', part: '', },
	code: { iso: '104', iso2: 'mm', iso3: 'MMR', ean: '', phone: '+95', },
	internet: { wiki_ua: '%D0%9C%27%D1%8F%D0%BD%D0%BC%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'nam',
	title: { ua: 'Намібія', en: 'Namibia', },
	geo: { capital: 'windhoek', part: 'africa', },
	code: { iso: '516', iso2: 'na', iso3: 'NAM', ean: '', phone: '+264', },
	internet: { wiki_ua: '%D0%9D%D0%B0%D0%BC%D1%96%D0%B1%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'npl',
	title: { ua: 'Непал', en: 'Nepal', },
	geo: { capital: 'kathmandu', part: 'asia', },
	code: { iso: '524', iso2: 'np', iso3: 'NPL', ean: '', phone: '+977', },
	internet: { wiki_ua: '%D0%9D%D0%B5%D0%BF%D0%B0%D0%BB', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'ner',
	title: { ua: 'Нігер', en: 'Niger', },
	geo: { capital: 'niamey', part: 'africa', },
	code: { iso: '562', iso2: 'ne', iso3: 'NER', ean: '', phone: '+227', },
	internet: { wiki_ua: '%D0%9D%D1%96%D0%B3%D0%B5%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'nga',
	title: { ua: 'Нігерія', en: 'Nigeria', },
	geo: { capital: 'abuja', part: 'africa', },
	code: { iso: '566', iso2: 'ng', iso3: 'NGA', ean: '', phone: '', },
	internet: { wiki_ua: '%D0%9D%D1%96%D0%B3%D0%B5%D1%80%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'nld', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Нідерланди', en: 'Netherlands', },
	geo: { capital: 'amsterdam', part: 'europe', },
	code: { iso: '528', iso2: 'nl', iso3: 'NLD', ean: '87', phone: '+31', },
	internet: { wiki_ua: '%D0%9D%D1%96%D0%B4%D0%B5%D1%80%D0%BB%D0%B0%D0%BD%D0%B4%D0%B8', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 17333790, year: 2019, },
	area: 41526,
},
{
	id: 'nic',
	title: { ua: 'Нікарагуа', en: 'Nicaragua', },
	geo: { capital: 'managua', part: 'amer_n', },
	code: { iso: '558', iso2: 'ni', iso3: 'NIC', ean: '743', phone: '+505', },
	internet: { wiki_ua: '%D0%9D%D1%96%D0%BA%D0%B0%D1%80%D0%B0%D0%B3%D1%83%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'deu', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Німеччина', en: 'Germany', },
	geo: { capital: 'berlin', part: 'europe', },
	code: { iso: '276', iso2: 'de', iso3: 'DEU', ean: '400-440', phone: '+49', },
	internet: { wiki_ua: '%D0%9D%D1%96%D0%BC%D0%B5%D1%87%D1%87%D0%B8%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 83019200, year: 2019, },
	area: 357578,
},
{
	id: 'nzl',
	title: { ua: 'Нова Зеландія', en: 'New Zealand', },
	geo: { capital: 'wellington', part: 'oceania', },
	code: { iso: '554', iso2: 'nz', iso3: 'NZL', ean: '94', phone: '+64', },
	internet: { wiki_ua: '%D0%9D%D0%BE%D0%B2%D0%B0_%D0%97%D0%B5%D0%BB%D0%B0%D0%BD%D0%B4%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 4596700, year: 2015, },
	area: 268680,
},
{
	id: 'nor', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Норвегія', en: 'Norway', },
	geo: { capital: 'oslo', part: 'europe', },
	code: { iso: '578', iso2: 'no', iso3: 'NOR', ean: '70', phone: '+47', },
	internet: { wiki_ua: '%D0%9D%D0%BE%D1%80%D0%B2%D0%B5%D0%B3%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 5488984, year: 2023, },
	area: 385207,
},
{
	id: 'are',
	title: { ua: 'ОАЕ', en: 'UAE', },
	geo: { capital: 'abu_dhabi', part: 'asia', },
	code: { iso: '784', iso2: 'ae', iso3: 'ARE', ean: '', phone: '+971', },
	internet: { wiki_ua: '%D0%9E%D0%B1%27%D1%94%D0%B4%D0%BD%D0%B0%D0%BD%D1%96_%D0%90%D1%80%D0%B0%D0%B1%D1%81%D1%8C%D0%BA%D1%96_%D0%95%D0%BC%D1%96%D1%80%D0%B0%D1%82%D0%B8', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 9992083, year: 2020, },
	area: 83600,
},
{
	id: 'omn',
	title: { ua: 'Оман', en: 'Oman', },
	geo: { capital: 'muscat', part: 'asia', },
	code: { iso: '512', iso2: 'om', iso3: 'OMN', ean: '', phone: '+968', },
	internet: { wiki_ua: '%D0%9E%D0%BC%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 3424386, year: 2017, },
	area: 309500,
},
{
	id: 'pak',
	title: { ua: 'Пакистан', en: 'Pakistan', },
	geo: { capital: 'islamabad', part: 'asia', },
	code: { iso: '586', iso2: 'pk', iso3: 'PAK', ean: '', phone: '+92', },
	internet: { wiki_ua: '%D0%9F%D0%B0%D0%BA%D0%B8%D1%81%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 206139589, year: 2020, },
	area: 803940,
},
{
	id: 'pse',
	title: { ua: 'Палестина', en: 'Palestine', },
	geo: { capital: 'ramallah', part: '', },
	code: { iso: '275', iso2: 'ps', iso3: 'PSE', ean: '', phone: '+970', },
	internet: { wiki_ua: '%D0%9F%D0%B0%D0%BB%D0%B5%D1%81%D1%82%D0%B8%D0%BD%D1%81%D1%8C%D0%BA%D0%B0_%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%B2%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 5101414, year: 2020, },
	area: 6020,
},
{
	id: 'pan',
	title: { ua: 'Панама', en: 'Panama', },
	geo: { capital: 'panama', part: '', },
	code: { iso: '591', iso2: 'pa', iso3: 'PAN', ean: '745', phone: '+507', },
	internet: { wiki_ua: '%D0%9F%D0%B0%D0%BD%D0%B0%D0%BC%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 3661868, year: 2013, },
	area: 75517,
},
{
	id: 'png',
	title: { ua: 'Папуа Нова Гвінея', en: 'Papua New Guinea', },
	geo: { capital: 'port_moresby', part: 'oceania', },
	code: { iso: '598', iso2: 'pg', iso3: 'PNG', ean: '', phone: '+675', },
	internet: { wiki_ua: '%D0%9F%D0%B0%D0%BF%D1%83%D0%B0_%D0%9D%D0%BE%D0%B2%D0%B0_%D0%93%D0%B2%D1%96%D0%BD%D0%B5%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 8251162, year: 2017, },
	area: 462840,
},
{
	id: 'zaf',
	title: { ua: 'ПАР', en: 'South African Republic', },
	geo: { capital: 'pretoria', part: 'africa', },
	code: { iso: '4710', iso2: 'za', iso3: 'ZAF', ean: '', phone: '+27', },
	internet: { wiki_ua: '%D0%9F%D1%96%D0%B2%D0%B4%D0%B5%D0%BD%D0%BD%D0%BE-%D0%90%D1%84%D1%80%D0%B8%D0%BA%D0%B0%D0%BD%D1%81%D1%8C%D0%BA%D0%B0_%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'pry',
	title: { ua: 'Парагвай', en: 'Paraguay', },
	geo: { capital: 'asuncion', part: 'amer_s', },
	code: { iso: '600', iso2: 'py', iso3: 'PRY', ean: '784', phone: '+595', },
	internet: { wiki_ua: '%D0%9F%D0%B0%D1%80%D0%B0%D0%B3%D0%B2%D0%B0%D0%B9', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'per',
	title: { ua: 'Перу', en: 'Peru', },
	geo: { capital: 'lima', part: 'amer_s', },
	code: { iso: '604', iso2: 'pe', iso3: 'PER', ean: '775', phone: '+51', },
	internet: { wiki_ua: '%D0%9F%D0%B5%D1%80%D1%83', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'kor',
	title: { ua: 'Південна Корея', en: 'South Korea', },
	geo: { capital: 'seoul', part: 'asia', },
	code: { iso: '410', iso2: 'kr', iso3: 'KOR', ean: '880', phone: '+82', },
	internet: { wiki_ua: '%D0%9F%D1%96%D0%B2%D0%B4%D0%B5%D0%BD%D0%BD%D0%B0_%D0%9A%D0%BE%D1%80%D0%B5%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 51529338, year: 2015, },
	area: 100363,
},
{
	id: 'ssd',
	title: { ua: 'Південний Судан', en: 'South Sudan', },
	geo: { capital: 'juba', part: 'africa', },
	code: { iso: '728', iso2: 'ss', iso3: 'SSD', ean: '', phone: '+211', },
	internet: { wiki_ua: '%D0%9F%D1%96%D0%B2%D0%B4%D0%B5%D0%BD%D0%BD%D0%B8%D0%B9_%D0%A1%D1%83%D0%B4%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 11193725, year: 2020, },
	area: 619745,
},
{
	id: 'prk',
	title: { ua: 'Північна Корея', en: 'North Korea', },
	geo: { capital: 'pyongyang', part: 'asia', },
	code: { iso: '408', iso2: 'kp', iso3: 'PRK', ean: '867', phone: '+850', },
	internet: { wiki_ua: '%D0%9F%D1%96%D0%B2%D0%BD%D1%96%D1%87%D0%BD%D0%B0_%D0%9A%D0%BE%D1%80%D0%B5%D1%8F', },	
	independence_day: { dm: '1508', descr: 'ind', wiki_ua: '', },
	population: { count: 25713000, year: 2019, },
	area: 120540,
},
{
	id: 'pol', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Польща', en: 'Poland', },
	geo: { capital: 'warszawa', part: 'europe', },
	code: { iso: '616', iso2: 'pl', iso3: 'POL', ean: '590', phone: '+48', },
	internet: { wiki_ua: '%D0%9F%D0%BE%D0%BB%D1%8C%D1%89%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 38265000, year: 2020, },
	area: 312685,
},
{
	id: 'prt', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Португалія', en: 'Portugal', },
	geo: { capital: 'lisbon', part: 'europe', },
	code: { iso: '620', iso2: 'pt', iso3: 'PRT', ean: '560', phone: '+351', },
	internet: { wiki_ua: '%D0%9F%D0%BE%D1%80%D1%82%D1%83%D0%B3%D0%B0%D0%BB%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'pri',
	title: { ua: 'Пуерто-Рико', en: 'Puerto Rico', },
	geo: { capital: 'san_juan', part: 'amer_n', },
	code: { iso: '630', iso2: 'pr', iso3: 'PRI', ean: '', phone: '+1(787), 1(939)', },
	internet: { wiki_ua: '%D0%9F%D1%83%D0%B5%D1%80%D1%82%D0%BE-%D0%A0%D0%B8%D0%BA%D0%BE', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'rus',
	title: { ua: 'Росія', en: 'Russia', },
	geo: { capital: 'moscow', part: 'eurasia', },
	code: { iso: '643', iso2: 'ru', iso3: 'RUS', ean: '460-469', phone: '+7', },
	internet: { wiki_ua: '%D0%A0%D0%BE%D1%81%D1%96%D1%8F', },
	independence_day: { dm: '1206', descr: 'state', wiki_ua: '', },
	population: { count: 142998511, year: 2020, },
	area: 17098246,
},
{
	id: 'rwa',
	title: { ua: 'Руанда', en: 'Rwanda', },
	geo: { capital: 'kigali', part: 'africa', },
	code: { iso: '646', iso2: 'rw', iso3: 'RWA', ean: '', phone: '+250', },
	internet: { wiki_ua: '%D0%A0%D1%83%D0%B0%D0%BD%D0%B4%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 11262564, year: 2015, },
	area: 26798,
},
{
	id: 'rou', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Румунія', en: 'Romania', },
	geo: { capital: 'bucharest', part: 'europe', },
	code: { iso: '642', iso2: 'ro', iso3: 'ROU', ean: '594', phone: '+40', },
	internet: { wiki_ua: '%D0%A0%D1%83%D0%BC%D1%83%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 19053815, year: 2022, },
	area: 238397,
},
{
	id: 'slv',
	title: { ua: 'Сальвадор', en: 'Salvador', },
	geo: { capital: 'san_salvador', part: 'amer_n', },
	code: { iso: '222', iso2: 'sv', iso3: 'SLV', ean: '741', phone: '+503', },
	internet: { wiki_ua: '%D0%A1%D0%B0%D0%BB%D1%8C%D0%B2%D0%B0%D0%B4%D0%BE%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 6141350, year: 2015, },
	area: 21040,
},
{
	id: 'wsm',
	title: { ua: 'Самоа', en: 'Samoa', },
	geo: { capital: 'apia', part: 'oceania', },
	code: { iso: '882', iso2: 'ws', iso3: 'WSM', ean: '', phone: '+685', },
	internet: { wiki_ua: '%D0%90%D0%BF%D1%96%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 179000, year: 2009, },
	area: 2831,
},
{
	id: 'smr', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Сан-Марино', en: 'San Marino', },
	geo: { capital: 'san_marino', part: 'europe', },
	code: { iso: '674', iso2: 'sm', iso3: 'SMR', ean: '', phone: '+378', },
	internet: { wiki_ua: '%D0%A1%D0%B0%D0%BD-%D0%9C%D0%B0%D1%80%D0%B8%D0%BD%D0%BE', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 32284, year: 212, },
	area: 61,
},
{
	id: 'sau',
	title: { ua: 'Саудівська Аравія', en: 'Saudi Arabia', },
	geo: { capital: 'riyadh', part: 'asia', },
	code: { iso: '682', iso2: 'sa', iso3: 'SAU', ean: '628', phone: '+966', },
	internet: { wiki_ua: '%D0%A1%D0%B0%D1%83%D0%B4%D1%96%D0%B2%D1%81%D1%8C%D0%BA%D0%B0_%D0%90%D1%80%D0%B0%D0%B2%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'sen',
	title: { ua: 'Сенегал', en: 'Senegal', },
	geo: { capital: 'dakar', part: 'africa', },
	code: { iso: '686', iso2: 'sn', iso3: 'SEN', ean: '', phone: '+221', },
	internet: { wiki_ua: '%D0%A1%D0%B5%D0%BD%D0%B5%D0%B3%D0%B0%D0%BB', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 13567338, year: 2013, },
	area: 196723,
},
{
	id: 'srb', symbol: { flag: 1, coa: 1, },
	yug: 1,
	title: { ua: 'Сербія', en: 'Serbia', },
	geo: { capital: 'belgrade', part: 'europe', },
	code: { iso: '688', iso2: 'rs', iso3: 'SRB', ean: '', phone: '+381', },
	internet: { wiki_ua: '%D0%A1%D0%B5%D1%80%D0%B1%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'syr',
	title: { ua: 'Сирія', en: 'Syria', },
	geo: { capital: 'damascus', part: 'asia', },
	code: { iso: '760', iso2: 'sy', iso3: 'SYR', ean: '621', phone: '+963', },
	internet: { wiki_ua: '%D0%A1%D0%B8%D1%80%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 17500658, year: 2020, },
	area: 185180,
},
{
	id: 'sgp',
	title: { ua: 'Сінгапур', en: 'Singapore', },
	geo: { capital: '', part: 'asia', },
	code: { iso: '702', iso2: 'sg', iso3: 'SGP', ean: '888', phone: '+65', },
	internet: { wiki_ua: '%D0%A1%D1%96%D0%BD%D0%B3%D0%B0%D0%BF%D1%83%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'svk', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Словаччина', en: 'Slovakia', },
	geo: { capital: 'bratislava', part: 'europe', },
	code: { iso: '703', iso2: 'sk', iso3: 'SVK', ean: '858', phone: '+421', },
	internet: { wiki_ua: '%D0%A1%D0%BB%D0%BE%D0%B2%D0%B0%D1%87%D1%87%D0%B8%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 5456000, year: 2019, },
	area: 49036,
},
{
	id: 'svn', symbol: { flag: 1, coa: 1, },
	yug: 1,
	title: { ua: 'Словенія', en: 'Slovenia', },
	geo: { capital: 'lublyana', part: 'europe', },
	code: { iso: '705', iso2: 'si', iso3: 'SVN', ean: '383', phone: '', },
	internet: { wiki_ua: '%D0%A1%D0%BB%D0%BE%D0%B2%D0%B5%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 2061085, year: 2017, },
	area: 20273,
},
{
	id: 'som',
	title: { ua: 'Сомалі', en: 'Somalia', },
	geo: { capital: 'mogadishu', part: 'africa', },
	code: { iso: '706', iso2: 'so', iso3: 'SOM', ean: '', phone: '+252', },
	internet: { wiki_ua: '%D0%A1%D0%BE%D0%BC%D0%B0%D0%BB%D1%96', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 10251568, year: 2013, },
	area: 637661,
},
{
	id: 'usa',
	title: { ua: 'США', en: 'USA', },
	geo: { capital: 'washington', part: 'amer_n', },
	code: { iso: '840', iso2: 'us', iso3: 'USA', ean: '00-13', phone: '+1', },
	internet: { wiki_ua: '%D0%A1%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D1%96_%D0%A8%D1%82%D0%B0%D1%82%D0%B8_%D0%90%D0%BC%D0%B5%D1%80%D0%B8%D0%BA%D0%B8', },
	independence_day: { dm: '0407', descr: 'ind', wiki_ua: '', },
	population: { count: 328915700, year: 2019, },
	area: 9826675,
},
{
	id: 'sdn',
	title: { ua: 'Судан', en: 'Sudan', },
	geo: { capital: 'khartoum', part: 'africa', },
	code: { iso: '729', iso2: 'sd', iso3: 'SDN', ean: '', phone: '+249', },
	internet: { wiki_ua: '%D0%A1%D1%83%D0%B4%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 43849260, year: 2020, },
	area: 1886068,
},
{
	id: 'sur',
	title: { ua: 'Суринам', en: 'Suriname', },
	geo: { capital: 'paramaribo', part: 'amer_n', },
	code: { iso: '740', iso2: 'sr', iso3: 'SUR', ean: '', phone: '+597', },
	internet: { wiki_ua: '%D0%A1%D1%83%D1%80%D0%B8%D0%BD%D0%B0%D0%BC', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 585824, year: 2016, },
	area: 163820,
},
{
	id: 'sle',
	title: { ua: 'Сьєрра-Леоне', en: 'Sierra Leone', },
	geo: { capital: 'freetown', part: 'africa', },
	code: { iso: '694', iso2: 'sl', iso3: 'SLE', ean: '', phone: '+232', },
	internet: { wiki_ua: '%D0%A1%D1%8C%D1%94%D1%80%D1%80%D0%B0-%D0%9B%D0%B5%D0%BE%D0%BD%D0%B5', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 7092113, year: 2015, },
	area: 71740,
},
{
	id: 'tjk',
	title: { ua: 'Таджикистан', en: 'Tajikistan', },
	geo: { capital: 'dushanbe', part: 'asia', },
	code: { iso: '762', iso2: 'tj', iso3: 'TJK', ean: '488', phone: '+992', },
	internet: { wiki_ua: '%D0%A2%D0%B0%D0%B4%D0%B6%D0%B8%D0%BA%D0%B8%D1%81%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'tha',
	title: { ua: 'Таїланд', en: 'Thailand', },
	geo: { capital: 'bangkok', part: 'asia', },
	code: { iso: '764', iso2: 'th', iso3: 'THA', ean: '885', phone: '+66', },
	internet: { wiki_ua: '%D0%A2%D0%B0%D1%97%D0%BB%D0%B0%D0%BD%D0%B4', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 69799978, year: 2020, },
	area: 514000,
},
{
	id: 'twn',
	title: { ua: 'Тайвань', en: 'Taiwan', },
	geo: { capital: 'taipei', part: 'asia', },
	code: { iso: '158', iso2: 'tw', iso3: 'TWN', ean: '471', phone: '+886', },
	internet: { wiki_ua: '%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B0_%D0%9A%D0%B8%D1%82%D0%B0%D0%B9', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 23451837, year: 2021, },
	area: 36197,
},
{
	id: 'tza',
	title: { ua: 'Танзанія', en: 'Tanzania', },
	geo: { capital: 'dodoma', part: 'africa', },
	code: { iso: '834', iso2: 'tz', iso3: 'TZA', ean: '', phone: '+255', },
	internet: { wiki_ua: '%D0%A2%D0%B0%D0%BD%D0%B7%D0%B0%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 46912768, year: 2012, },
	area: 945087,
},
{
	id: 'tgo',
	title: { ua: 'Того', en: 'Togo', },
	geo: { capital: 'lome', part: 'africa', },
	code: { iso: '768', iso2: 'tg', iso3: 'TGO', ean: '', phone: '+228', },
	internet: { wiki_ua: '%D0%A2%D0%BE%D0%B3%D0%BE', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 6100000, year: 2005, },
	area: 56785,
},
{
	id: 'tto',
	title: { ua: 'Тринідад і Тобаго', en: 'Trinidad and Tobago', },
	geo: { capital: 'port_of_spain', part: 'amer_s', },
	code: { iso: '780', iso2: 'tt', iso3: 'TTO', ean: '', phone: '+868', },
	internet: { wiki_ua: '%D0%A2%D1%80%D0%B8%D0%BD%D1%96%D0%B4%D0%B0%D0%B4_%D1%96_%D0%A2%D0%BE%D0%B1%D0%B0%D0%B3%D0%BE', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'tuv',
	title: { ua: 'Тувалу', en: 'Tuvalu', },
	geo: { capital: 'funafuti', part: 'oceania', },
	code: { iso: '798', iso2: 'tv', iso3: 'TUV', ean: '', phone: '+688', },
	internet: { wiki_ua: '%D0%A2%D1%83%D0%B2%D0%B0%D0%BB%D1%83', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 10544, year: 2011, },
	area: 26,
},
{
	id: 'tun',
	title: { ua: 'Туніс', en: 'Tunisia', },
	geo: { capital: 'tunisia', part: 'africa', },
	code: { iso: '788', iso2: 'tn', iso3: 'TUN', ean: '619', phone: '+216', },
	internet: { wiki_ua: '%D0%A2%D1%83%D0%BD%D1%96%D1%81', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 11403800, year: 2017, },
	area: 163610,
},
{
	id: 'tur',
	title: { ua: 'Туреччина', en: 'Turkey', },
	geo: { capital: 'ankara', part: 'asia', },
	code: { iso: '792', iso2: 'tr', iso3: 'TUR', ean: '869', phone: '+90', },
	internet: { wiki_ua: '%D0%A2%D1%83%D1%80%D0%B5%D1%87%D1%87%D0%B8%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 80810525, year: 2017, },
	area: 783356,
},
{
	id: 'tkm',
	title: { ua: 'Туркменістан', en: 'Turkmenistan', },
	geo: { capital: 'ashgabat', part: 'asia', },
	code: { iso: '795', iso2: 'tm', iso3: 'TKM', ean: '483', phone: '+993', },
	internet: { wiki_ua: '%D0%A2%D1%83%D1%80%D0%BA%D0%BC%D0%B5%D0%BD%D1%96%D1%81%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 5942000, year: 2019, },
	area: 488100,
},
{
	id: 'uga',
	title: { ua: 'Уганда', en: 'Uganda', },
	geo: { capital: 'kampala', part: 'africa', },
	code: { iso: '800', iso2: 'ug', iso3: 'UGA', ean: '', phone: '+256', },
	internet: { wiki_ua: '%D0%A3%D0%B3%D0%B0%D0%BD%D0%B4%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 45741007, year: 2020, },
	area: 236040,
},
{
	id: 'hun', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Угорщина', en: 'Hungary', },
	geo: { capital: 'budapest', part: 'europe', },
	code: { iso: '348', iso2: 'hu', iso3: 'HUN', ean: '599', phone: '+36', },
	internet: { wiki_ua: '%D0%A3%D0%B3%D0%BE%D1%80%D1%89%D0%B8%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'uzb',
	title: { ua: 'Узбекистан', en: 'Uzbekistan', },
	geo: { capital: 'tashkent', part: 'asia', },
	code: { iso: '860', iso2: 'uz', iso3: 'UZB', ean: '478', phone: '+998', },
	internet: { wiki_ua: '%D0%A3%D0%B7%D0%B1%D0%B5%D0%BA%D0%B8%D1%81%D1%82%D0%B0%D0%BD', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'ukr', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Україна', en: 'Ukraine', },
	geo: { capital: 'kyiv', part: 'europe', }, 
	code: { iso: '804', iso2: 'ua', iso3: 'UKR', ean: '482', phone: '+380', },
	internet: { wiki_ua: '%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B0', },
	independence_day: '2408',
	population: { count: 48457000, year: 2001, },
	area: 603700,
},
{
	id: 'ury',
	title: { ua: 'Уругвай', en: 'Uruguay', },
	geo: { capital: 'montevideo', part: 'amer_s', },
	code: { iso: '858', iso2: 'uy', iso3: 'URY', ean: '773', phone: '+598', },
	internet: { wiki_ua: '%D0%A3%D1%80%D1%83%D0%B3%D0%B2%D0%B0%D0%B9', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 3473730, year: 2020, },
	area: 176215,
},
{
	id: 'fji',
	title: { ua: 'Фіджі', en: 'Fiji', },
	geo: { capital: 'suva', part: 'oceania', },
	code: { iso: '242', iso2: 'fj', iso3: 'FJI', ean: '', phone: '+679', },
	internet: { wiki_ua: '%D0%A4%D1%96%D0%B4%D0%B6%D1%96', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'phl',
	title: { ua: 'Філіппіни', en: 'Philippines', },
	geo: { capital: 'manila', part: 'asia', },
	code: { iso: '608', iso2: 'ph', iso3: 'PHL', ean: '480', phone: '+63', },
	internet: { wiki_ua: '%D0%A4%D1%96%D0%BB%D1%96%D0%BF%D0%BF%D1%96%D0%BD%D0%B8', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'fin', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Фінляндія', en: 'Finland', },
	geo: { capital: 'helsinki', part: 'europe', },
	code: { iso: '246', iso2: 'fi', iso3: 'FIN', ean: '64', phone: '+358', },
	internet: { wiki_ua: '%D0%A4%D1%96%D0%BD%D0%BB%D1%8F%D0%BD%D0%B4%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'fra', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Франція', en: 'France', },
	geo: { capital: 'paris', part: 'europe', },
	code: { iso: '250', iso2: 'fr', iso3: 'FRA', ean: '30-37', phone: '+33', },
	internet: { wiki_ua: '%D0%A4%D1%80%D0%B0%D0%BD%D1%86%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 66842134, year: 2016, },
	area: 551595,
},
{
	id: 'hrv', symbol: { flag: 1, coa: 1, },
	yug: 1, 
	title: { ua: 'Хорватія', en: 'Croatia', },
	geo: { capital: 'zagreb', part: 'europe', },
	code: { iso: '191', iso2: 'hr', iso3: 'HRV', ean: '385', phone: '+385', },
	internet: { wiki_ua: '%D0%A5%D0%BE%D1%80%D0%B2%D0%B0%D1%82%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'caf',
	title: { ua: 'ЦАР', en: 'CAR', },
	geo: { capital: 'bungee', part: 'africa', },
	code: { iso: '140', iso2: 'cf', iso3: 'CAF', ean: '', phone: '+236', },
	internet: { wiki_ua: '%D0%A6%D0%B5%D0%BD%D1%82%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B0%D1%84%D1%80%D0%B8%D0%BA%D0%B0%D0%BD%D1%81%D1%8C%D0%BA%D0%B0_%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'tcd',
	title: { ua: 'Чад', en: 'Chad', },
	geo: { capital: 'ndjamena', part: 'africa', },
	code: { iso: '148', iso2: 'td', iso3: 'TCD', ean: '', phone: '+235', },
	internet: { wiki_ua: '%D0%A7%D0%B0%D0%B4', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 10146000, year: 2005, },
	area: 1284000,
},
{
	id: 'cze', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Чехія', en: 'Czech Republic', },
	geo: { capital: 'prague', part: 'europe', },
	code: { iso: '203', iso2: 'cz', iso3: 'CZE', ean: '859', phone: '+420', },
	internet: { wiki_ua: '%D0%A7%D0%B5%D1%85%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 10637540, year: 2019, },
	area: 78866,
},
{
	id: 'chl',
	title: { ua: 'Чилі', en: 'Chile', },
	geo: { capital: '', part: 'amer_s', },
	code: { iso: '152', iso2: 'cl', iso3: 'CHL', ean: '780', phone: '+56', },
	internet: { wiki_ua: '%D0%A7%D0%B8%D0%BB%D1%96', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 17574003, year: 2017, },
	area: 756096,
},
{
	id: 'mne', yug: 1,
	title: { ua: 'Чорногорія', en: 'Montenegro', },
	geo: { capital: 'podgorica', part: '', },
	code: { iso: '499', iso2: 'me', iso3: 'MNE', ean: '', phone: '+382', },
	internet: { wiki_ua: '%D0%A7%D0%BE%D1%80%D0%BD%D0%BE%D0%B3%D0%BE%D1%80%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
},
{
	id: 'che', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Швейцарія', en: 'Switzerland', },
	geo: { capital: 'bern', part: 'europe', },
	code: { iso: '756', iso2: 'ch', iso3: 'CHE', ean: '76', phone: '+41', },
	internet: { wiki_ua: '%D0%A8%D0%B2%D0%B5%D0%B9%D1%86%D0%B0%D1%80%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 8401120, year: 2016, },
	area: 41285,
},
{
	id: 'swe', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Швеція', en: 'Sweden', },
	geo: { capital: 'stockholm', part: 'europe', },
	code: { iso: '752', iso2: 'se', iso3: 'SWE', ean: '73', phone: '+46', },
	internet: { wiki_ua: '%D0%A8%D0%B2%D0%B5%D1%86%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 9354462, year: 2009, },
	area: 449964,
},
{
	id: 'lka',
	title: { ua: 'Шрі-Ланка', en: 'Sri Lanka', },
	geo: { capital: 'sri_jayawardenepura_kotte', part: 'asia', },
	code: { iso: '144', iso2: 'lk', iso3: 'LKA', ean: '479', phone: '+94', },
	internet: { wiki_ua: '%D0%A8%D1%80%D1%96-%D0%9B%D0%B0%D0%BD%D0%BA%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 21919000, year: 2020, },
	area: 65610,
},
{
	id: 'jam',
	title: { ua: 'Ямайка', en: 'Jamaica', },
	geo: { capital: 'kingston', part: 'amer_n', },
	code: { iso: '388', iso2: 'jm', iso3: 'JAM', ean: '', phone: '+876', },
	internet: { wiki_ua: '%D0%AF%D0%BC%D0%B0%D0%B9%D0%BA%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 2651000, year: 2005, },
	area: 11500,
},
{
	id: 'jpn',
	title: { ua: 'Японія', en: 'Japan', },
	geo: { capital: 'tokyo', part: 'asia', },
	code: { iso: '392', iso2: 'jp', iso3: 'JPN', ean: '45, 49', phone: '+81', },
	internet: { wiki_ua: '%D0%AF%D0%BF%D0%BE%D0%BD%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 126476461, year: 2020, },
	area: 377972,
},










// неіснуючі держави

{
	id: 'bur',
	title: { ua: 'Бірма', en: 'Burma', },
	geo: { capital: 'naypedo', part: 'asia', },
	code: { iso: '104', iso2: 'bu', iso3: 'BUR', ean: '', phone: '+95', },
	internet: { wiki_ua: '%D0%9C%27%D1%8F%D0%BD%D0%BC%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 54409800, year: 2020, },
	area: 676578,
	not_exist: 1,
},
{
	id: 'zar',
	title: { ua: 'Заїр', en: 'Zaire', },
	geo: { capital: 'kinshasa', part: 'asia', },
	code: { iso: '180', iso2: 'zr', iso3: 'ZAR', ean: '', phone: '', },
	internet: { wiki_ua: '%D0%97%D0%B0%D1%97%D1%80', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	population: { count: 46498539, year: 1996, },
	area: 2345410,
	not_exist: 1,
},
{
	id: 'sun',
	title: { ua: 'СРСР', en: 'USSR', },
	geo: { capital: 'moscow', part: 'eurasia', },
	code: { iso: '810', iso2: 'su', iso3: 'SUN', ean: '', phone: '', },
	internet: { wiki_ua: '%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D1%81%D0%BE%D1%8E%D0%B7%D0%BD%D0%B8%D1%85_%D1%80%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA_%D0%A1%D0%A0%D0%A1%D0%A0', },
	independence_day: { dm: '3012', note: 'Подписание договора об образовании СССР', },
	not_exist: 1,
},
{
	id: 'csk', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Чехословаччина', en: 'Czechoslovakia', },
	geo: { capital: 'prague', part: 'europe', },
	code: { iso: '200', iso2: 'cs', iso3: 'CSK', ean: '', phone: '', },
	internet: { wiki_ua: '%D0%A7%D0%B5%D1%85%D0%BE%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%87%D1%87%D0%B8%D0%BD%D0%B0', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	not_exist: 1,
},
{
	id: 'yug', symbol: { flag: 1, coa: 1, },
	title: { ua: 'Югославія', en: 'Yugoslavia', },
	geo: { capital: 'belgrade', part: 'europe', },
	code: { iso: '891', iso2: 'yu', iso3: 'YUG', ean: '860', phone: '+38', },
	internet: { wiki_ua: '%D0%AE%D0%B3%D0%BE%D1%81%D0%BB%D0%B0%D0%B2%D1%96%D1%8F', },
	independence_day: { dm: '', descr: '', note: '', wiki_ua: '', },
	not_exist: 1,
},
{
	id: 'rem', 	// вигаданий неіснуючий код
	symbol: { coa: 1, },
	title: { ua: 'Російська Імперія', en: 'Russian Empire', },
	geo: { capital: 'st_petersburg', part: 'eurasia', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	internet: { wiki_ua: '%D0%A0%D0%BE%D1%81%D1%96%D0%B9%D1%81%D1%8C%D0%BA%D0%B0_%D1%96%D0%BC%D0%BF%D0%B5%D1%80%D1%96%D1%8F', },
	independence_day: { dm: '', note: '', },
	not_exist: 1,
},
{
	id: 'rom', 	// вигаданий неіснуючий код
	title: { ua: 'Стародавній Рим', en: 'Ancient Rome', },
	geo: { capital: 'rome', part: 'europe', },
	code: { iso: '', iso2: '', iso3: '', ean: '', phone: '', },
	internet: { wiki_ua: '%D0%A1%D1%82%D0%B0%D1%80%D0%BE%D0%B4%D0%B0%D0%B2%D0%BD%D1%96%D0%B9_%D0%A0%D0%B8%D0%BC', },
	independence_day: { dm: '', note: '', },
	not_exist: 1,
},









];





let objCountry = {};
arrCountry.forEach( k => {
	objCountry[ k.id ] = k;
});





const arrCountry1 = [



'ukr',
'usa',
'can',
'fra',
'gbr',
'deu',
'ita',
'jpn',
'',

'aus',
'aut',
'aze',
'alb',
'dza',
'ago',
'and',
'arg',
'afg',
'brb',
'bgd',
'bhr',
'blz',
'bel',
'ben',
'blr',
'bgr',
'bol',
'bih',
'bwa',
'bra',
'brn',
'btn',
'vat',
'ven',
'vnm',
'arm',
'gab',
'hti',
'gmb',
'gha',
'guy',
'gtm',
'gin',
'gnb',
'gib',
'hnd',
'hkg',
'grl',
'grc',
'geo',
'dnk',
'dji',
'dma',
'ecu',
'gnq',
'eri',
'est',
'eth',
'egy',
'yem',
'zmb',
'zwe',
'isr',
'ind',
'idn',
'irq',
'irn',
'irl',
'isl',
'esp',
'jor',
'kaz',
'khm',
'cmr',
'qat',
'ken',
'kgz',
'chn',
'cyp',
'kir',
'col',
'cod',
'cog',
'cri',
'civ',
'cub',
'kwt',
'lao',
'lva',
'lso',
'ltu',
'lbr',
'lbn',
'lby',
'lie',
'lux',
'mrt',
'mdg',
'mkd',
'mys',
'mli',
'mlt',
'mar',
'mex',
'moz',
'mda',
'mco',
'mng',
'mmr',
'nam',
'npl',
'ner',
'nga',
'nld',
'nic',
'nzl',
'nor',
'are',
'omn',
'pak',
'pse',
'pan',
'png',
'zaf',
'pry',
'per',
'kor',
'ssd',
'prk',
'pol',
'prt',
'pri',
'rus',
'rwa',
'rou',
'slv',
'wsm',
'smr',
'sau',
'sen',
'srb',
'syr',
'sgp',
'svk',
'svn',
'som',
'sdn',
'sur',
'sle',
'tjk',
'tha',
'twn',
'tza',
'tgo',
'tto',
'tuv',
'tun',
'tur',
'tkm',
'uga',
'hun',
'uzb',
'ury',
'fji',
'phl',
'fin',
'hrv',
'caf',
'tcd',
'cze',
'chl',
'mne',
'che',
'swe',
'lka',
'jam',
'bur',
'zar',
'sun',
'csk',
'yug',
'rem',
'rom',


];




/*


Бар-Код	
https://romario-auto.com/pages/news/74/


609	Маврикий
746	Доминиканская Республика
958	Макау





Телефоны

https://www.ixbt.com/mobile/country_code.html

https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BB%D0%B5%D1%84%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5_%D0%BA%D0%BE%D0%B4%D1%8B_%D1%81%D1%82%D1%80%D0%B0%D0%BD







*/






